### ISSUE TITLE
Incompatible with Majrusz's Accessories (Local Server Crash)

### ISSUE THREAD

**Issue by GolfinhoVoador** [avivbeeri/kintsugi#1]
Happening in 1.20.1 with Kintsugi 0.1.0 and Majrusz's Accessories 1.2.3 and its library.
I forgot to create an Issue here, but I created an [issue in the other mod's page too](https://github.com/Majrusz/MajruszsAccessories/issues/20).

Crash log:
[crash-2023-09-19_20.45.27-server.txt](https://github.com/avivbeeri/kintsugi/files/12731178/crash-2023-09-19_20.45.27-server.txt)

**Comment by avivbeeri** [comment]
Thank you for reporting this, and even trying to give Kintsugi a go.
I think that this is an issue on my side and I'll have it fixed in the next release.

Kintsugi isn't really built with mod-compatibility in mind, so I would expect that even with that fix, there are likely to be other incompatibilities.

**Comment by GolfinhoVoador** [comment]
> Thank you for reporting this, and even trying to give Kintsugi a go. I think that this is an issue on my side and I'll have it fixed in the next release.
> 
> Kintsugi isn't really built with mod-compatibility in mind, so I would expect that even with that fix, there are likely to be other incompatibilities.

No problem, this is a very good mod btw!

**Comment by avivbeeri** [comment]
I'm hoping this has been rectified with version 0.1.1, please give this a go.

I'm going to close this for now, but please re-open if it's still an issue.
