### ISSUE TITLE
Incompatible with Zeta (Quark api) (Exception in server tick loop when enter local world)

### ISSUE THREAD

**Issue by raykoshima** [avivbeeri/kintsugi#2]
Game version 1.20.1 Kintsugi version 0.1.1 Zeta version 1.0-13 Quark version 4.0-435
work fine without Quark mod install

crash-report
[crash-2024-02-10_20.45.14-server.txt](https://github.com/avivbeeri/kintsugi/files/14229488/crash-2024-02-10_20.45.14-server.txt)

**Comment by avivbeeri** [comment]
Hi there!

Kintsugi makes some heavy-handed changes to villager trading, which can make it incompatible with other mods.

I've found the cause of this particular crash, but I make no guarantees that Kintsugi will be compatible with the rest of Zeta, since it makes some very deep changes to the way that Enchantments and the Anvil work.
