### ISSUE TITLE
How to level up the base enchantments given at the start

### ISSUE THREAD

**Issue by raffel080108** [avivbeeri/kintsugi#3]
How do you access higher levels of sharpness, power, unbreaking or protection for example? There doesn't seem to exist books of knowledge for those unless they just dont show up in the creative menu for some reason.

From what I could find, all the other enchantments are leveled by just stacking a lot of books of the same type in the bookshelves near the table
From my testing:
Level 2 = 3 Books
Level 3 = 9 Books
Level 4 = 18 Books
Level 5 = 30 Books

**Comment by avivbeeri** [comment]
Hi there! Thank you for giving Kintsugi a look and exploring its mechanics.

Sharpness, Power, Unbreaking and Protection are some of the "default" enchantments. You can always access them in the Enchanter, which is why no book is present or needed.

When you add extra books onto the bookshelves, it raises the maximum level that you can enchant any enchantment to (up to the maximum that enchantment allows).

You control which level of enchantment you create by adding a number of lapis equal to that level. You can see a little blue gauge on the interface to show you available levels.

As an example, if you have 9 books on the shelf, you can enchant Sharpness at level 3, if you put 3 lapis into the enchanting interface.

I'm fairly sure that you have to put unique books on the shelves for it to count towards the maximum level, but I need to double check.

**Comment by raffel080108** [comment]
Yes, I understand they are available at the start, but I don't know how to access higher levels of "default" enchantments. Can you explain this?
Also what do you mean "unique" books? Are the knowledge books tagged/keyed with uuids/ids when they are generated? I was in creative mode and middle clicking to copy books, so the nbt would be the same (and the books still worked apparently)

**Comment by raffel080108** [comment]
Just putting lapis in does not increase the available enchantment level of default enchantments. They are effectively locked to Level 1 in the current state unless I am doing it wrong somehow

**Comment by avivbeeri** [comment]
By "unique" I meant knowledge books for different enchantments, rather than the same enchantments. Not UUIDs or similar.

I haven't thought about some of this for a while, but I think that because you're playing in creative, you might have stumbled on a strange bug. I need to investigate more and then I'll get back to you.

**Comment by raffel080108** [comment]
How would being in creative cause the available levels of default enchantments to be incorrect?

**Comment by avivbeeri** [comment]
I've just been looking into this, and as far as I can tell, everything is working correctly, even in creative.

The available level of enchantments increases when more books are placed in the bookshelves.
Adding additional lapis selects which level of enchantment you actually want.

![Screenshot_20240402_075507](https://github.com/avivbeeri/kintsugi/assets/1446063/6bb5d741-a11f-4110-87fa-50663d006353)

**Comment by raffel080108** [comment]
Still doesn't answer my question of how to get knowledge books for the "default" enchantments because I still could not find a way to get those even in creative or with a mod similar to JEI (or whatever it's called these days)

**Comment by avivbeeri** [comment]
I don't understand why you need knowledge books for the defaults, there's
no use for them.
